region          = "us-east-1"
environment     = "poc"
acm_domain_name = "*.arc-poc.link"
#container_image_override = "884360309640.dkr.ecr.us-east-1.amazonaws.com/sourcefuse-backstage:0.1.0"
namespace = "arc"
