---
name:  "Deploy Backstage Prod"

on:            # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Docker Push"]
    types:
      - completed
    paths:
      - 'terraform/*'
      - '.github/workflows/deploy-backstage-prod.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## run terraform apply
  plan:
    name: Deploy - Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
    outputs:
      plan_id: ${{ steps.workflow_vars.outputs.plan_id }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # install aws cli
      - name: Install AWS CLI
        shell: bash
        run: ./scripts/dependencies/install-aws-cli.sh
        continue-on-error: false

      # install tfenv
      - name: Install tfenv
        shell: bash
        run: ./scripts/dependencies/install-tfenv.sh
        continue-on-error: false

      # Setup plan id for plan exports
      - name: Set outputs
        id: workflow_vars
        run: |
          echo "plan_id=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      # configure iam
      - name: Configure IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/arc-prod-terraform-backstage-deploy
          aws-region: us-east-1
        continue-on-error: false

#      - name: Create AWS config
#        shell: pwsh
#        run: |
#          ./scripts/action-credentials-to-file.ps1 ${{ vars.PLAN_ENV }}
#        continue-on-error: false

      # initialize backend
      - name: Initialize backend
        shell: bash
        run: |
          ./scripts/action-init-plan-apply.sh -i prod
        continue-on-error: false

      # Running plan
      - name: Plan against Prod
        id: prod_plan
        shell: bash
        run: |
          ./scripts/action-init-plan-apply.sh -a prod
        continue-on-error: false

        #publish plan to artifacts
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: "prod-${{ steps.workflow_vars.outputs.plan_id }}.tfplan"
          path: "terraform/prod-${{ steps.workflow_vars.outputs.plan_id }}.tfplan"
        continue-on-error: false

      - name: Update plan output to pr
        uses: mshick/add-pr-comment@v2
        with:
          message-id: prod-tfplan
          message-path: "terraform/prod-plan-output.txt"
        continue-on-error: false
