name: Docker CI

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
     branches:
       - "feature/*"

jobs:
  build-and-push-to-ecr:
    name: build-image
    runs-on:
      - self-hosted
      - arc

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.SF_REF_ARCH_AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.SF_REF_ARCH_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.SF_REF_ARCH_AWS_REGION }}

#      - name: Build, tag, and push image to Amazon ECR
#        env:
#          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#        run: |
#          export IMAGE_TAG=$(cat version.json | jq -r .version)
#          ./scripts/docker-build-tag-and-push.sh
      - name: docker-compose build
        run: docker-compose build
