---
name: Docker Build

on:            # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: docker-compose build
