name: Docker CI

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
     branches:
       - "feature/*"

jobs:
  build-and-push-to-ecr:
    runs-on:
      - self-hosted
      - refarch
      - dev
    name: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SF_REF_ARCH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SF_REF_ARCH_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SF_REF_ARCH_AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: latest
          ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          # Build a docker compose and push it to ECR 
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$env:ACCOUNT".dkr.ecr.us-east-1.amazonaws.com.dkr.ecr.us-east-1.amazonaws.com
          docker-compose -f ./docker-compose.yml build 
          echo "Tagging Image..."
          docker tag sourcefuse/sourcefuse-backstage:"$env:IMAGE_TAG" $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/sf-refarch-dev-sourcefuse-backstage:$IMAGE_TAG
          echo "Pushing image to ECR..."
          docker push $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/sf-refarch-dev-sourcefuse-backstage:$IMAGE_TAG
          echo "::set-output name=image::$ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/sf-refarch-dev-sourcefuse-backstage:$IMAGE_TAG"
