name: Docker CI

on:
  push:
    tags:
      - 'dev-*'

jobs:

  build-and-push-to-ecr:
    runs-on:
      - self-hosted
      - refarch
    name: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SF_REF_ARCH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SF_REF_ARCH_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SF_REF_ARCH_AWS_REGION }}
      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@master
        with:
          access_key: ${{ secrets.SF_REF_ARCH_AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.SF_REF_ARCH_SECRET_ACCESS_KEY }}
          region: ${{ secrets.SF_REF_ARCH_AWS_REGION }}
      - name: Set output
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build, tag, and push the image to Amazon ECR
        id: build-push-image
        uses: aevea/action-kaniko@master  
        with:
          name: ${{ secrets.SF_REF_ARCH_REPO_NAME }}
          tag: ${{ steps.release.outputs.tag }}
          registry: ${{ steps.ecr.outputs.registry }}
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}